server:
  port: 8761
  
spring:
  application:
    name: fun-service-eureka

security:
  user:
    name: fun20180817
    password: fun20180817
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    response-cache-update-interval-ms: 5000
    eviction-interval-timer-in-ms: 5000
    enableSelfPreservation: true
    renewalPercentThreshold: 0.49
    peer-node-read-timeout-ms: 500
    peer-node-connect-timeout-ms: 500
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:     
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/      





  
  
  
